import { hexToBin } from '@bitauth/libauth';

import {
  Contract,
  Network,
  TransactionBuilder,
  type Artifact,
  type NetworkProvider,
  type Utxo,
} from 'cashscript';

import cashOutSettlementArtifactJson from 'src/contracts/artifacts/CashOutSettlement.json';

import { resolveCashOutSettlementDestinations } from 'src/services/cash-out-settlement-destinations';

import { buildCashOutSettlementPlanFromRecord } from 'src/services/cash-out-settlement-plan';

import type { CashOutRecord } from 'src/types/cash-out';

import type {
  CashOutSettlementContractPlan,
  CashOutSettlementFeePlanningIteration,
  CashOutSettlementP2pkhDestination,
  CashOutSettlementPlan,
} from 'src/types/cash-out-settlement';

/**
 * Normal Cash-out settlement policy.
 *
 * Keep this explicit rather than relying on a TransactionBuilder default.
 */
export const CASH_OUT_SETTLEMENT_FEE_RATE_SATS_PER_BYTE = 1;

const MAX_FEE_PLANNING_ITERATIONS = 20;

const CASH_OUT_COMMITMENT_HEX_PATTERN = /^[0-9a-f]{64}$/;

const ZERO_CASH_OUT_COMMITMENT_HEX = '0'.repeat(64);

/**
 * The artifact is generated by our pinned cashc compiler before the settlement
 * suite runs.
 */
const CASH_OUT_SETTLEMENT_ARTIFACT =
  cashOutSettlementArtifactJson as unknown as Artifact;

/**
 * Fixed synthetic outpoint used ONLY to calculate the exact serialized size
 * of the future one-input settlement transaction.
 *
 * A real txid:vout is deliberately not known during D1.
 *
 * txid and vout always occupy the same serialized number of bytes, so this
 * produces the same transaction size as the later real selected payment UTXO.
 */
const SETTLEMENT_SIZE_PROBE_TXID = '00'.repeat(32);

function requireCashOutCommitmentHex(value: string): string {
  const normalized =
    typeof value === 'string' ? value.trim().toLowerCase() : '';

  if (!CASH_OUT_COMMITMENT_HEX_PATTERN.test(normalized)) {
    throw new Error(
      'Cash-out settlement commitment must be exactly 32 bytes encoded as hexadecimal.'
    );
  }

  if (normalized === ZERO_CASH_OUT_COMMITMENT_HEX) {
    throw new Error('Cash-out settlement commitment must not be zero.');
  }

  return normalized;
}

function bigintToPositiveSafeInteger(value: bigint, fieldName: string): number {
  const converted = Number(value);

  if (
    !Number.isSafeInteger(converted) ||
    converted <= 0 ||
    BigInt(converted) !== value
  ) {
    throw new Error(`${fieldName} must be a positive safe integer.`);
  }

  return converted;
}

function createSettlementCandidate(input: {
  cashOut: CashOutRecord;

  cashOutCommitmentHex: string;

  provider: NetworkProvider;

  treasuryDestination: CashOutSettlementP2pkhDestination;

  platformDestination: CashOutSettlementP2pkhDestination;

  settlementFeeSats: number;
}): {
  settlementPlan: CashOutSettlementPlan;

  contract: Contract;

  transactionBuilder: TransactionBuilder;
} {
  const settlementPlan = buildCashOutSettlementPlanFromRecord({
    cashOut: input.cashOut,

    treasuryDestination: input.treasuryDestination,

    platformDestination: input.platformDestination,

    settlementFeeSats: input.settlementFeeSats,
  });

  const contract = new Contract(
    CASH_OUT_SETTLEMENT_ARTIFACT,
    [
      hexToBin(input.cashOutCommitmentHex),

      hexToBin(settlementPlan.constructor.treasuryPublicKeyHashHex),

      hexToBin(settlementPlan.constructor.platformPublicKeyHashHex),

      BigInt(settlementPlan.constructor.paymentSats),

      BigInt(settlementPlan.constructor.platformFeeSats),

      BigInt(settlementPlan.constructor.settlementFeeSats),
    ],
    {
      provider: input.provider,

      /**
       * Freeze the normal settlement contract type explicitly.
       *
       * CashScript 0.13.2 currently defaults to P2SH32, but production identity
       * must not depend on an implicit SDK default.
       */
      contractType: 'p2sh32',
    }
  );

  if (contract.contractType !== 'p2sh32') {
    throw new Error(
      'Cash-out settlement contract did not instantiate as P2SH32.'
    );
  }

  const settlementSizeProbeUtxo: Utxo = {
    txid: SETTLEMENT_SIZE_PROBE_TXID,

    vout: 0,

    satoshis: BigInt(settlementPlan.paymentSats),
  };

  const settleUnlockerFactory = contract.unlock['settle'];

  if (typeof settleUnlockerFactory !== 'function') {
    throw new Error(
      'Cash-out settlement artifact does not expose the settle() covenant function.'
    );
  }

  const transactionBuilder = new TransactionBuilder({
    provider: input.provider,

    /**
     * Safety ceilings only.
     *
     * The covenant itself fixes the exact miner fee economically.
     */
    maximumFeeSatoshis: 10_000n,

    maximumFeeSatsPerByte: 10,
  })
    .addInput(settlementSizeProbeUtxo, settleUnlockerFactory())
    .addOutput({
      to: settlementPlan.treasuryDestination.address,

      amount: BigInt(settlementPlan.treasuryOutputSats),
    })
    .addOutput({
      to: settlementPlan.platformDestination.address,

      amount: BigInt(settlementPlan.platformOutputSats),
    });

  return {
    settlementPlan,

    contract,

    transactionBuilder,
  };
}

export interface BuildCashOutSettlementContractPlanInput {
  cashOut: CashOutRecord;

  /**
   * Unique 32-byte commitment for this one Cash-out contract instance.
   *
   * D1 accepts this as an already-frozen value.
   *
   * Phase E will generate and durably persist it before the customer contract
   * address/QR is exposed.
   */
  cashOutCommitmentHex: string;

  /**
   * Merchant Treasury master mainnet P2PKH address.
   */
  treasuryAddress: string;

  /**
   * Optional test/runtime override.
   *
   * Production callers normally omit this and use PLATFORM_FEE_ADDRESS through
   * resolveCashOutSettlementDestinations().
   */
  platformAddress?: string;

  /**
   * The CashScript SDK needs a provider to determine the network and construct
   * transaction objects.
   *
   * No network query or broadcast occurs in this planner.
   */
  provider: NetworkProvider;
}

/**
 * Build one deterministic, production-shaped normal Cash-out settlement
 * contract plan.
 *
 * This performs the fixed-point miner-fee loop against the REAL instantiated
 * CashScript contract.
 *
 * Nothing is persisted or broadcast.
 */
export function buildCashOutSettlementContractPlan(
  input: BuildCashOutSettlementContractPlanInput
): CashOutSettlementContractPlan {
  if (input.provider.network !== Network.MAINNET) {
    throw new Error(
      'Cash-out settlement contract planning requires a Bitcoin Cash mainnet provider.'
    );
  }

  const cashOutCommitmentHex = requireCashOutCommitmentHex(
    input.cashOutCommitmentHex
  );

  const destinations = resolveCashOutSettlementDestinations({
    treasuryAddress: input.treasuryAddress,

    platformAddress: input.platformAddress,
  });

  const feePlanningIterations: CashOutSettlementFeePlanningIteration[] = [];

  let proposedSettlementFeeSats = 1;

  for (
    let iteration = 1;
    iteration <= MAX_FEE_PLANNING_ITERATIONS;
    iteration += 1
  ) {
    const candidate = createSettlementCandidate({
      cashOut: input.cashOut,

      cashOutCommitmentHex,

      provider: input.provider,

      treasuryDestination: destinations.treasuryDestination,

      platformDestination: destinations.platformDestination,

      settlementFeeSats: proposedSettlementFeeSats,
    });

    const transactionSizeBigInt =
      candidate.transactionBuilder.getTransactionSize();

    const requiredSettlementFeeBigInt =
      transactionSizeBigInt *
      BigInt(CASH_OUT_SETTLEMENT_FEE_RATE_SATS_PER_BYTE);

    const transactionSizeBytes = bigintToPositiveSafeInteger(
      transactionSizeBigInt,
      'Cash-out settlement transaction size'
    );

    const requiredSettlementFeeSats = bigintToPositiveSafeInteger(
      requiredSettlementFeeBigInt,
      'Cash-out required settlement miner fee'
    );

    feePlanningIterations.push({
      iteration,

      proposedSettlementFeeSats,

      transactionSizeBytes,

      requiredSettlementFeeSats,
    });

    if (requiredSettlementFeeSats === proposedSettlementFeeSats) {
      const actualFee = candidate.transactionBuilder.calculateTransactionFee();

      if (actualFee.feeSats !== BigInt(proposedSettlementFeeSats)) {
        throw new Error(
          'Cash-out settlement transaction fee does not equal the frozen contract miner fee.'
        );
      }

      if (
        actualFee.feeSatsPerByte !== CASH_OUT_SETTLEMENT_FEE_RATE_SATS_PER_BYTE
      ) {
        throw new Error(
          'Cash-out settlement transaction does not satisfy the frozen fee-rate policy.'
        );
      }

      if (!candidate.contract.address.startsWith('bitcoincash:')) {
        throw new Error(
          'Cash-out settlement contract did not produce a mainnet CashAddr.'
        );
      }

      if (
        candidate.contract.bytecode.length !==
        candidate.contract.bytesize * 2
      ) {
        throw new Error(
          'Cash-out settlement contract bytecode identity does not match its reported byte size.'
        );
      }

      return {
        version: 'cash_out_settlement_contract_v1',

        settlementPlan: candidate.settlementPlan,

        cashOutCommitmentHex,

        constructor: {
          cashOutCommitmentHex,

          ...candidate.settlementPlan.constructor,
        },

        contractType: 'p2sh32',

        contractAddress: candidate.contract.address,

        contractLockingBytecodeHex:
          candidate.contract.lockingBytecode.toLowerCase(),

        contractBytecodeHex: candidate.contract.bytecode.toLowerCase(),

        contractBytecodeSize: candidate.contract.bytesize,

        contractOpcodeCount: candidate.contract.opcount,

        settlementTransactionSizeBytes: transactionSizeBytes,

        settlementFeeRateSatsPerByte:
          CASH_OUT_SETTLEMENT_FEE_RATE_SATS_PER_BYTE,

        feePlanningIterations,
      };
    }

    proposedSettlementFeeSats = requiredSettlementFeeSats;
  }

  throw new Error('Cash-out settlement miner-fee planning did not converge.');
}
